Fix setoutput
ONSdigital/rm-survey-service pull request #136
Opened 2022-12-20 09:23 UTC by SteveScorfield

# What and why?
Removal of deprecated github action
# How to test?

# Trello
https://trello.com/c/JyPxSmDA/2298-replace-soon-to-be-deprecated-set-output-in-github-actions

2022-12-20 09:24 UTC, SteveScorfield commented
![](https://github.trello.services/images/mini-trello-icon.png) [Replace soon to be deprecated `set-output` in github actions](https://trello.com/c/JyPxSmDA/2298-replace-soon-to-be-deprecated-set-output-in-github-actions)

2022-12-21 11:33 UTC, matthew-robinson-ons commented
/deploy robinm3

2022-12-21 11:38 UTC, matthew-robinson-ons requested changes

2022-12-21 11:38 UTC, matthew-robinson-ons commented on .github/workflows/main.yml
> +          cho "version=$(grep -E "appVersion:\s+" $CHART_DIRECTORY/Chart.yaml | cut -d" " -f2 | sed -r 's/"//g')" >> $GITHUB_OUTPUT
missing the 'e' off echo

2022-12-22 10:31 UTC, matthew-robinson-ons approved these changes

2022-12-22 12:59 UTC, merged